@endpoint = http://localhost:3000/api/v1/dishes

###
# @name postADish
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: 1234567890

{
  "name": "Brownie",
  "price": 8,
  "ingredients": [
    {
      "name": "chocolate",
      "quantity": "100g"
    },
    {
      "name": "vegetable oil",
      "quantity": "50ml"
    },
    {
      "name": "sugar",
      "quantity": "50g"
    },
    {
      "name": "flour",
      "quantity": "50g"
    }
  ],
  "allergens": [
    {
      "name": "dairy",
      "ingredients": "chocolate"      
    },
    {
      "name": "gluten",
      "ingredients": ["flour"]
    }
  ],
  "availability": {
    "menu": "dessert",
    "special": false
  }
}
###
@newDish = {{postADish.response.body._id}}

###
GET  {{endpoint}} HTTP/3.0
content-type: application/json
x-api-key: 1234567890
###
GET  {{endpoint}}/{{newDish}} HTTP/3.0
content-type: application/json



###

DELETE  {{endpoint}}/{{newDish}} HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/{{newDish}} HTTP/3.0
content-type: application/json

###
GET  http://localhost:1610/stormlight HTTP/3.0
content-type: application/json

###